repos:
  - repo: local
    hooks:
      - id: system
        name: Poetry check
        entry: poetry check
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Requirements
        entry: poetry export --format=requirements.txt --without-hashes --dev --output=requirements.txt
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black pymtgfall/
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort pymtgfall/
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy pymtgfall/
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint pymtgfall/
        pass_filenames: false
        language: system